#!/bin/bash/

# Create a new environment and run the following
# May need more packages installed, these were the ones
#   not included in the basic conda env creation

# For python version 3.8

conda install plotly
conda install pandas
conda install -c anaconda pillow
conda install -c conda-forge/label/cf202003 pypng
conda install -c conda-forge/label/cf202003 opencv
